import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const cjsPath = path.join(repoRoot, "dist", "occt-js.js");
const esmPath = path.join(repoRoot, "dist", "occt-js.mjs");

const cjsSource = readFileSync(cjsPath, "utf8");

const umdFooterPattern = /\r?\nif \(typeof exports === 'object' && typeof module === 'object'\)\r?\n  module\.exports = OcctJS;\r?\nelse if \(typeof define === 'function' && define\['amd'\]\)\r?\n  define\(\[\], \(\) => OcctJS\);\s*$/;
if (!umdFooterPattern.test(cjsSource)) {
  throw new Error(`Could not find expected UMD footer in ${cjsPath}.`);
}

let esmSource = cjsSource.replace(umdFooterPattern, "\n");

const scriptNamePattern = /var _scriptName = typeof document != 'undefined' \? document\.currentScript\?\.src : undefined;/;
if (!scriptNamePattern.test(esmSource)) {
  throw new Error(`Could not find expected _scriptName bootstrap in ${cjsPath}.`);
}

esmSource = esmSource.replace(
  scriptNamePattern,
  [
    "var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;",
    "  if (!_scriptName && typeof import.meta === \"object\" && typeof import.meta.url === \"string\") _scriptName = import.meta.url;",
  ].join("\n"),
);

esmSource += "\nexport default OcctJS;\n";

writeFileSync(
  esmPath,
  [
    "// Auto-generated from dist/occt-js.js by tools/generate_esm_runtime_entry.mjs.",
    "// Do not edit this file directly; regenerate it after rebuilding the Wasm runtime.",
    "",
    esmSource,
  ].join("\n"),
  "utf8",
);

console.log(`Generated ${path.relative(repoRoot, esmPath)} from ${path.relative(repoRoot, cjsPath)}.`);
